STRINGS = {
    "basket_header_budget": "سلة محسّنة ضمن الميزانية لزيادة التوفير:",
    "basket_header_cart": "تم تطبيق العروض على عناصر السلة التي اخترتها:",
    "basket_header_reorder": "اقتراحات إعادة الطلب بناءً على سلالك الأخيرة:",
    "basket_header_recommendation": "اقتراحات ذكية بناءً على التوقعات والأكثر مبيعًا في منطقتك:",

    "mode_label": "الوضع",
    "promo_label": "عرض",
    "offer_label": "العرض",
    "discount_label": "الخصم",
    "price_label": "السعر",
    "discounted_price_label": "بعد الخصم",
    "subtotal_label": "الإجمالي الفرعي",
    "total_discount_label": "إجمالي الخصم",
    "grand_total_label": "الإجمالي النهائي",
    "profit_label": "الربح",
    "profit_margin_label": "هامش الربح",
    "item_total_label": "إجمالي الصنف",
    "saving_label": "التوفير",

    "cta_added_to_cart": "أضفت هذه العناصر إلى سلتك. هل تريد تعديل شيء أو إضافة المزيد؟",
    "cta_cart_empty_add_recommendations": "كانت سلتك فارغة. هل تريد أن أضيف هذه التوصيات إلى السلة؟",
    "cta_recommendations_choose_items": "هذه توصياتك. ما العناصر التي تريد إضافتها إلى الطلب؟",
    "cta_finalize": "هل نُكمل التأكيد أم تريد تعديل شيء؟",

    "basket_no_suitable_prefix": "تعذر إنشاء طلب مناسب بالمدخلات الحالية",
    "basket_no_suitable_message": "يرجى تعديل الميزانية أو إضافة أصناف أو المحاولة بعد قليل.",
    "item_fallback_index": "صنف {index}",
    "item_fallback_generic": "صنف",

    "promotions_none": "لا توجد عروض نشطة لهذه العناصر حالياً.",
    "promotions_unavailable": "بيانات العروض غير متاحة حالياً. حاول مرة أخرى بعد قليل.",
    "promotions_intro_pdf_sent": "تم إرسال ملف PDF للعروض على واتساب (الأعلى خصماً أولاً).",
    "promotions_intro_pdf_failed": "تعذر إرسال ملف PDF للعروض، وهذه أهم النقاط:",
    "promotions_intro_pdf_generation_failed": "تعذر إنشاء ملف PDF للعروض الآن؛ إليك أهم النقاط بالأسفل:",
    "promotions_intro_top_with_pdf_hint": "هذه أفضل العروض (يتطلب PDF وجود user_id صالح):",
    "promotions_intro_active": "هذه العروض النشطة:",
    "promotions_more_skus": "+{count} أصناف إضافية",
    "promotions_more_offers_pdf": "...و{count} عرضاً إضافياً موجوداً في ملف PDF.",
    "promotions_more_offers_active": "...و{count} عروض نشطة إضافية.",
    "promotions_special_price": "سعر خاص",
    "promotions_special_offer": "عرض خاص",
    "promotion_item_fallback": "صنف ترويجي",
    "promotions_pdf_caption": "العروض مرتبة حسب أعلى خصم.",
    "promotions_pdf_title": "العروض الحالية",
    "promotions_pdf_subtitle": "مرتبة حسب أعلى خصم أولاً",
    "pdf_column_item_name": "اسم الصنف",

    "top_sellers_unavailable": "بيانات الأكثر مبيعاً غير متاحة حالياً. حاول مرة أخرى بعد قليل.",
    "top_sellers_intro": "هذه أكثر المنتجات مبيعاً الآن:",
    "top_sellers_intro_with_limit": "هذه أفضل {limit} منتجات مبيعاً الآن:",

    "unknown_error": "خطأ غير معروف",
    "auth_missing_user_id": "مطلوب التحقق: user_id مفقود.",
    "system_error_missing_api_token": "خطأ نظام: API_JWT_TOKEN مفقود.",
    "system_error_missing_tenant_id": "خطأ نظام: TENANT_ID مفقود.",
    "budget_invalid_max_budget": "إعدادات الميزانية غير صحيحة: يرجى إدخال max_budget موجب.",
    "reorder_not_enabled": "وضع إعادة الطلب غير مفعّل بعد. فعّل SALES_INTEL_REORDER_ENABLED=1 بعد جاهزية الخلفية.",
    "invalid_request_verify_inputs": "يبدو أن الطلب غير صالح؛ يرجى التحقق من المدخلات.",
    "invalid_request": "يبدو أن الطلب غير صالح.",
    "system_error_status": "خطأ نظام ({status}): {detail}",
    "connection_error": "خطأ اتصال: قد تكون هناك مشكلة في النظام. ({detail})",
    "err_known_2001": "بيانات التوقعات غير كافية - تم استخدام قالب بديل",
    "err_known_2002": "لا توجد عروض مناسبة",
    "err_known_3001": "إعدادات الميزانية غير صحيحة",
    "err_known_4001": "لا يوجد سجل طلبات",
    "err_known_4002": "نطاق التاريخ غير صالح",
}
