STRINGS = {
    "basket_header_budget": "Budget ke hisaab se best basket (savings max) aap ke limit mein:",
    "basket_header_cart": "Aap ke selected cart items pe promotions apply karke:",
    "basket_header_reorder": "Aap ke recent baskets ke hisaab se reorder recommendations:",
    "basket_header_recommendation": "Smart recommendations (forecast  area bestsellers) ke hisaab se:",

    "mode_label": "Mode",
    "promo_label": "Promo",
    "offer_label": "Offer",
    "discount_label": "Discount",
    "price_label": "Price",
    "discounted_price_label": "Discounted",
    "subtotal_label": "Subtotal",
    "total_discount_label": "Total Discount",
    "grand_total_label": "Grand Total",
    "profit_label": "Profit",
    "profit_margin_label": "Profit Margin",
    "item_total_label": "Item Total",
    "saving_label": "Saving",

    "cta_added_to_cart": "Yeh items cart mein add kar diye hain. Koi change karna hai ya kuch aur add karna hai?",
    "cta_cart_empty_add_recommendations": "Aap ka cart empty tha. Kya yeh recommendations cart mein add kar doon?",
    "cta_recommendations_choose_items": "Yeh recommendations ready hain. Bata dein kin items ko order mein add karna hai?",
    "cta_finalize": "Confirm karna hai ya koi change karna hai? Bata dein.",

    "basket_no_suitable_prefix": "Current inputs se suitable order generate nahi ho saka",
    "basket_no_suitable_message": "Budget adjust karein, SKUs add karein, ya thori der baad dobara try karein.",
    "item_fallback_index": "Item {index}",
    "item_fallback_generic": "Item",

    "promotions_none": "In items par abhi koi active promotion available nahi.",
    "promotions_unavailable": "Promotions data abhi available nahi. Thori der baad dobara try karein.",
    "promotions_intro_pdf_sent": "Promotions PDF WhatsApp par share kar di hai (highest discounts pehle).",
    "promotions_intro_pdf_failed": "Promotions PDF send nahi ho saki, lekin highlights yahan hain:",
    "promotions_intro_pdf_generation_failed": "Promotions PDF abhi generate nahi ho saki; highlights neeche hain:",
    "promotions_intro_top_with_pdf_hint": "Yeh top promotions hain (PDF bhejne ke liye valid user_id chahiye):",
    "promotions_intro_active": "Yeh active promotions hain:",
    "promotions_more_skus": "+{count} aur SKUs",
    "promotions_more_offers_pdf": "...aur {count} offers PDF mein cover hain.",
    "promotions_more_offers_active": "...aur {count} active offers.",
    "promotions_special_price": "Special price",
    "promotions_special_offer": "Special Offer",
    "promotion_item_fallback": "Promotion item",
    "promotions_pdf_caption": "Promotions highest discount ke hisaab se sort ki gayi hain.",
    "promotions_pdf_title": "Current Promotions",
    "promotions_pdf_subtitle": "Highest discount ke hisaab se sorted",
    "pdf_column_item_name": "Item Name",

    "top_sellers_unavailable": "Top sellers ka data abhi available nahi. Thori der baad dobara try karein.",
    "top_sellers_intro": "Yeh abhi ke top sellers hain:",
    "top_sellers_intro_with_limit": "Yeh abhi ke top {limit} sellers hain:",

    "unknown_error": "Unknown error",
    "auth_missing_user_id": "Authentication required: user_id missing hai.",
    "system_error_missing_api_token": "System Error: API_JWT_TOKEN missing.",
    "system_error_missing_tenant_id": "System Error: TENANT_ID missing.",
    "budget_invalid_max_budget": "Budget parameters invalid hain: positive max_budget dein.",
    "reorder_not_enabled": "Reorder Intelligence abhi active nahi hai. Backend live hone ke baad SALES_INTEL_REORDER_ENABLED=1 set karke enable karein.",
    "invalid_request_verify_inputs": "Request invalid lag rahi hai; inputs verify karein.",
    "invalid_request": "Request invalid lag rahi hai.",
    "system_error_status": "System Error ({status}): {detail}",
    "connection_error": "Connection Error: System issue ho sakta hai. ({detail})",
    "err_known_2001": "Forecast data kam hai - fallback template use hua",
    "err_known_2002": "Applicable promotions nahi mili",
    "err_known_3001": "Budget parameters invalid hain",
    "err_known_4001": "Order history nahi mili",
    "err_known_4002": "Date range invalid hai",
}
